name: NodeJS CI with PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

services:
  postgres:
    image: postgres:latest
    env: 
      POSTGRES_USER: codex
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: thegreet
    ports:
    - 5432:5432
    # Set health checks to wait until postgres has started
    options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
    
steps:
- uses: actions/checkout@v3
- name: Install dependencies
  run: npm install
- name: create postgresql tables
  run: PGPASSWORD=pg123 psql -h localhost -U codex -d thegreet -a -f ../sql/mydata.sql
- name: run tests with postgresql
  run:
    npm test
  env:
    DATABASE_URL: postgres://codex:pg123@localhost:5432/thegreet